### ISSUE TITLE
Backward compatibility with RISC-V Debug Specification 

### ISSUE THREAD

**Issue by gokhankaplayan** [joxie/riscv-debug-security#10]
When all privilege levels enabled by default in mdbgsec CSR, should we expect backward compatibility for external debug with the original RISC-V Debug Specification? 
Example Scenario: Core is halted when it is in U-mode (dcsr.prv = U-mode)
Assumptions: By default, all privilege levels are enabled (mdbgsec.dbgprv= U/S/M mode external debug enabled)
Behaviour of RISC-V External Debugger: Debugger will be able to access mstatus CSR when halted. 
Behaviour of RISC-V External Debugger+Secure Debug: Debugger will not be able to access mstatus CSR when halted. But, Debugger can still change dcsr.prv to M-mode since it is allowed in mdbgsec. Then, It can access to mstatus CSR.

**Comment by AoteJin** [comment]
Agree. If a platform would like to keep back-compatible, it should set the default value as debuggable for all privilege modes. If security is prefered, back-compatiblity is no more the case then, because back-compatiblity means unsecure.

**Comment by gokhankaplayan** [comment]
I agree that back-compatibility is not desired, if security is preferred. 
When the default values is debuggable for all privilege modes, the behaviour will be slightly different with the secure debug proposal. Please see the example scenario above.

**Comment by AoteJin** [comment]
change the behavior of all-enable cases for back-compatibility
