### ISSUE TITLE
Systemc Bus Access block protected by IOPMP/WG 

### ISSUE THREAD

**Issue by AoteJin** [joxie/riscv-debug-security#13]
In current prorosal, the system bus access is required to be checked against IOPMP/WG. But it seems not sufficient. Given the example:

1. The hart 0 grants debugger with machine mode privilege 
2. The hart 1 grants the supervisor mode privilege

The debugger should have differentiated accessiblity for each hart. However, regarding the current proposal, the debugger share the same system bus access rule even though two hart grants different privileges.
It seems a potential variant of Nailgun attack: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9667279

**Comment by joxie** [comment]
Debug access to system bus should be tagged with WID (World ID) or Domain ID, the spec can assume there's a module/mechanism outside of DM and controlled by M mode, that allows M mode to attach WID/DID to external debugger traffic

**Comment by gokhankaplayan** [comment]
I believe we need to define debugger authentication mechanism to assign source IDs when accessing in SBA so that IOPMP can apply different rules for different source IDs.  
In addition to the current RISC-V DM registers (authenticated, authbusy, and authdata), authentication ID register can be added to DM register.

**Comment by joxie** [comment]
Agree that we need an ID register and M mode to assign ID to debugger access to memory, but I am not sure we should bind ID with authentication as most implementations will need this without auth. I recommend leaving it to system implementation

One possible implementation is like below

![image](https://github.com/joxie/riscv-debug-security/assets/9899644/6a95af51-2d3f-4072-82ca-d1d936ece6ac)

**Comment by gokhankaplayan** [comment]
Device ID to SDID mapping looks software configurable. There is a recent progress in RISC-V IOPMP spec about it, but I cannot find where it is specified exactly. It is not part of the current IOPMP Specification. Is it implementation specific? 
I know my question is not primarily about Secure debug, it is more about IOPMP.

**Comment by joxie** [comment]
Yes, SDID is implementation specific in IOPMP spec as far as I know

**Comment by AoteJin** [comment]
I am think the case, if we have two hart, one is suppose to be the secure while the other non-secure. In this circumstance, is one Device ID enough to cover debug scenario for both of the core?

**Comment by joxie** [comment]
> I am think the case, if we have two hart, one is suppose to be the secure while the other non-secure. In this circumstance, is one Device ID enough to cover debug scenario for both of the core?

The mapping logic is controlled by M mode FW in my example above, other implementations may do this differently but principle should be the same.

In the case that external debugger is debugging non-secure hart, the SDID should be programmed to non-secure ID, such that the deviceID will be mapped to a non secure SDID and thus external debugger cannot access secure hart's memory

**Comment by AoteJin** [comment]
Close. The conclusion is documented in proposal
