### ISSUE TITLE
Mandate the behavior of asynchronous trigger 

### ISSUE THREAD

**Issue by AoteJin** [joxie/riscv-debug-security#16]
The implementation might have trigger fired asynchronously, e.g.:

1. The trigger is set for supervisor mode to enter debug mode 
2. The debugger is granted with supervior mode privilege 
3. The hart hit the trigger in supervisor mode 
4. The trigger is asynchronous and happen to fire off when privilege is already esclated to machine mode 

Such behavior should be avoided, otherwise it the less privileged debugger could be weaponized to attack higher privileged assets.

**Comment by AoteJin** [comment]
The asynchronous triggers should be rare. If the implementation opt for this, the implementation must assure that the pending trigger being fired before any privilege change to avoid potential privilege escalation. 
@AoteJin  to add this enforcement in proposal

**Comment by AoteJin** [comment]
@rsahita do you think this should be covered in RVI security mode as well?

**Comment by joxie** [comment]
Closing this issue, tracking at https://github.com/riscv-non-isa/riscv-external-debug-security/issues/14
