### ISSUE TITLE
Performance Counter enable for M-mode

### ISSUE THREAD

**Issue by gokhankaplayan** [joxie/riscv-debug-security#18]
Performance counters has configuration registers (mcyclecfg, minstretcfg) to isolate between privilege levels. HW RoT should be able control global enable for performance counters. For example, medbgen is a global enable for debug (+trace) here: https://github.com/riscv/riscv-smmtt/blob/main/chapter8.adoc

Similar mechanism seems missing for performance counters. Should we extend the scope for performance counters?

**Comment by pdonahue-ventana** [comment]
mcyclecfg and minstretcfg are analogous to the mhpmevent* CSRs from [Sscofpmf](https://github.com/riscv/riscv-count-overflow).  I don't think that there's anything missing here.  (Smcntrpmf is a more recent extension that was meant to fill the missing functionality for mcycle and minstret.)

**Comment by gokhankaplayan** [comment]
Thanks to Sscofpmf and Smcntrpmf, we have control to inhibit counting for different privilege levels by Hart CSRs. I have an additional question:
ARM has an external pin to enable non-invasive debug (which includes performance counters). It is controlled by a higher entity on CoT (E.g. HW RoT). I am not sure we have this requirement in RISC-V. It is not explicitly mentioned in SR_GEN_007 ([RISC-V security model](https://github.com/riscv-non-isa/riscv-security-model/blob/main/specification/src/chapter4.adoc#debug-and-performance-management))

**Comment by pdonahue-ventana** [comment]
I don't know of anything like this but I don't follow all of the security groups.

**Comment by joxie** [comment]
Closing this one, tracking all issues at official repo now
