### ISSUE TITLE
Alias of mdgbsec for S-mode, HS-mode and VS-mode

### ISSUE THREAD

**Issue by gokhankaplayan** [joxie/riscv-debug-security#8]
According to the proposed specification Machine Debug Security Control Register (mdbgsec) is WARL in M mode and not accessible for other privilege levels. 
The following scenarios require alias of mdgbsec for S-mode, HS-mode and VS-mode:
- OS context switching between user processes require alias of mdgbsec for S-mode.
- Hypervisor context switching between guest OSs require alias of mdgbsec for HS-mode.
- Guest OS context switching between VU-mode processes require alias of mdgbsec for VS-mode.

If debug enable per user processes and guest OSs is a requirement, the corresponding aliases should be added and one of the following approaches should be adopted: 
- OS/Hypervisor shall reprogram dgbsec CSR as part of context switching.  
- OS/Hypervisor shall program dgbsec CSR with required filtering (ASID for user processes and VMID for Guest OSs).

**Comment by AoteJin** [comment]
Considering the fact that self-hosted debug will be preferred if there is OS. I would say hypervisor being granted with privilege to control GuestOS/non-OS application debuggablility might be desired. But more extensive delegation to OS seems not neccessary and on the other hand kind of risky.

**Comment by joxie** [comment]
Discussed in TG meeting and email chain and didn't see objection, closing this ticket

https://lists.riscv.org/g/sig-debug-trace-perf-mon/message/216
